name: my_flutter_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

# Dependencies for the project
dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage: ^2.1.1
  dio: ^5.5.0+1
  flutter_local_notifications: ^17.2.1+1
  gap: ^3.0.1
  url_launcher: ^6.3.0
  internet_connection_checker_plus: ^2.5.0
  file_picker: ^8.0.6
  image_cropper: ^7.1.0
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  google_maps_flutter: ^2.9.0
  shared_preferences: ^2.3.2
  http: ^1.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0
  alice: ^0.4.2

# Flutter-specific settings
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/

# Flutter Launcher Icons configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Zip.png"
